#!/bin/sh
set -eu

csplit \
  --prefix 'slide' \
  --suffix-format '%02d.txt' \
  --silent \
  --suppress-matched \
  --elide-empty-files \
  "$1/slides.txt" \
  '/^$/' \
  '{*}'

mv ./slide??.txt "$1"
